CREATE TABLE "tbl_admin" (
  "id" SERIAL PRIMARY KEY,
  "username" varchar(100) NOT NULL,
  "password" varchar(100) NOT NULL,
  "is_deleted" boolean DEFAULT false,
  "role" varchar(25) DEFAULT 'admin'
);

CREATE TABLE "tbl_bank" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar(100),
  "bank_account" bigint UNIQUE,
  "account_name" varchar(100),
  "is_deleted" boolean DEFAULT false
);

CREATE TABLE "tbl_bank_admin" (
  "id" serial PRIMARY KEY,
  "admin_id" integer,
  "bank_id" integer
);

CREATE TABLE "tbl_bank_store" (
  "id" SERIAL PRIMARY KEY,
  "store_id" integer,
  "bank_id" integer
);

CREATE TABLE "tbl_membership" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar(100),
  "tax" double precision,
  "price" bigint,
  "is_deleted" boolean DEFAULT false
);

CREATE TABLE "tbl_owner" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar(100),
  "no_hp" varchar(15) UNIQUE,
  "email" varchar(100),
  "password" varchar(100),
  "membership_id" integer,
  "is_deleted" boolean DEFAULT false,
  "role" varchar(25) DEFAULT 'owner'
);

CREATE TABLE "tbl_store" (
  "id" SERIAL PRIMARY KEY,
  "name" varchar(100),
  "no_hp" varchar(15) UNIQUE,
  "email" varchar(100),
  "address" text,
  "is_deleted" boolean,
  "owner_id" integer
);

CREATE TABLE "tbl_product" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "price" bigint,
  "stock" integer,
  "description" text,
  "shipping_cost" integer,
  "merk_id" integer,
  "store_id" integer,
  "is_deleted" boolean DEFAULT false
);

CREATE TABLE "tbl_customer" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "no_hp" varchar(15) UNIQUE,
  "address" text,
  "password" varchar(100),
  "is_deleted" boolean DEFAULT false,
  "role" varchar(25) DEFAULT 'customer'
);

CREATE TABLE "tbl_chart" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quantity" smallint,
  "total"  double precision,
  "customer_id" integer,
  "product_id" integer,
  "is_deleted" boolean DEFAULT false
);

CREATE TABLE "tbl_merk" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "is_deleted" boolean DEFAULT false
);

CREATE TABLE "tbl_product_image" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "image_url" varchar(200),
  "product_id" integer
);

CREATE TABLE "tbl_transaction_order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quantity" integer,
  "total"  double precision,
  "customer_id" integer,
  "product_id" integer,
  "detail_order_id" integer
);

CREATE TABLE "tbl_transaction_detail_order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "buy_date" date,
  "status" varchar(100),
  "total_price"  double precision,
  "photo" varchar(200),
  "tax"  double precision,
  "virtual_account" bigint
);

CREATE TABLE "tbl_payment" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "transaction_detail_order_id" integer,
  "pay"  double precision
);

ALTER TABLE "tbl_bank_admin" ADD FOREIGN KEY ("admin_id") REFERENCES "tbl_admin" ("id");

ALTER TABLE "tbl_bank_admin" ADD FOREIGN KEY ("bank_id") REFERENCES "tbl_bank" ("id");

ALTER TABLE "tbl_bank_store" ADD FOREIGN KEY ("store_id") REFERENCES "tbl_store" ("id");

ALTER TABLE "tbl_bank_store" ADD FOREIGN KEY ("bank_id") REFERENCES "tbl_bank" ("id");

ALTER TABLE "tbl_owner" ADD FOREIGN KEY ("membership_id") REFERENCES "tbl_membership" ("id");

ALTER TABLE "tbl_store" ADD FOREIGN KEY ("owner_id") REFERENCES "tbl_owner" ("id");

ALTER TABLE "tbl_product" ADD FOREIGN KEY ("merk_id") REFERENCES "tbl_merk" ("id");

ALTER TABLE "tbl_product" ADD FOREIGN KEY ("store_id") REFERENCES "tbl_store" ("id");

ALTER TABLE "tbl_product_image" ADD FOREIGN KEY ("product_id") REFERENCES "tbl_product" ("id");

ALTER TABLE "tbl_chart" ADD FOREIGN KEY ("product_id") REFERENCES "tbl_product" ("id");

ALTER TABLE "tbl_chart" ADD FOREIGN KEY ("customer_id") REFERENCES "tbl_customer" ("id");

ALTER TABLE "tbl_payment" ADD FOREIGN KEY ("transaction_detail_order_id") REFERENCES "tbl_transaction_detail_order" ("id");

ALTER TABLE "tbl_transaction_order" ADD FOREIGN KEY ("customer_id") REFERENCES "tbl_customer" ("id");

ALTER TABLE "tbl_transaction_order" ADD FOREIGN KEY ("product_id") REFERENCES "tbl_product" ("id");

ALTER TABLE "tbl_transaction_order" ADD FOREIGN KEY ("detail_order_id") REFERENCES "tbl_transaction_detail_order" ("id");
